name: Run tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    # Configure the MySQL service
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Setup PHP 8.3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      # Install the Composer dependencies
      - name: Run composer install
        run: composer install -n --prefer-dist

      # Copy the .env.ci file to .env and generate the application key
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      # Run the tests
      - name: Run tests
        run: php artisan test
